import {
    Baby,
    Banknote,
    Book,
    Briefcase,
    Bus,
    Car,
    Coffee,
    CreditCard,
    Dumbbell,
    Film,
    Gamepad2,
    Gift,
    GraduationCap,
    Heart,
    Home,
    Music,
    PiggyBank,
    Plane,
    Shirt,
    ShoppingBag,
    ShoppingCart,
    Smartphone,
    Stethoscope,
    TrendingUp,
    TreePine,
    Utensils,
    Wallet,
    Wrench,
    Zap,
} from '@lucide/vue';
import type { Component } from '@lucide/vue';

export const CATEGORY_ICONS: Record<string, Component> = {
    shopping_cart: ShoppingCart,
    shopping_bag: ShoppingBag,
    home: Home,
    car: Car,
    bus: Bus,
    utensils: Utensils,
    coffee: Coffee,
    plane: Plane,
    heart: Heart,
    stethoscope: Stethoscope,
    briefcase: Briefcase,
    graduation_cap: GraduationCap,
    gift: Gift,
    music: Music,
    dumbbell: Dumbbell,
    shirt: Shirt,
    smartphone: Smartphone,
    film: Film,
    book: Book,
    wallet: Wallet,
    banknote: Banknote,
    credit_card: CreditCard,
    trending_up: TrendingUp,
    piggy_bank: PiggyBank,
    zap: Zap,
    wrench: Wrench,
    baby: Baby,
    tree_pine: TreePine,
    gamepad2: Gamepad2,
};
